name: CI

on:
  push:
    branches:
    - master
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: npm ci

    - name: ESLint checks
      uses: gimenete/eslint-action@1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  jest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: npm ci

    - name: Jest
      run: npm test
