name: CI

on:
  push:
    branches:
    - master
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: npm ci

    - name: ESLint checks
      run: npm run lint

  jest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: npm ci

    - name: Jest
      run: npm test
